import Footer from "@/components/global/Footer";
import Header from "@/components/global/Header";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable}`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>
        <div className="flex h-screen flex-col">
          <Header />
          <main className="flex-grow overflow-hidden">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
